# Generated by Django 5.2.5 on 2025-08-07 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT', 'Not'), ('DONE', 'Done'), ('YET', 'Yet')])),
                ('related_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos_api.category')),
            ],
        ),
    ]
