# Generated by Django 5.2.5 on 2025-08-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_color',
            field=models.CharField(max_length=50, null='Black'),
            preserve_default='Black',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('PLANNED', 'Planned')]),
        ),
    ]
